### ISSUE TITLE
rconcaveman

### ISSUE THREAD

**Issue by yonicd** [joelgombin/concaveman#1]
How would you go about randomly sampling from inside the hull?

**Comment by joelgombin** [comment]
I'm not sure what you mean exactly?

**Comment by yonicd** [comment]
drawing samples from inside the hull that concaveman creates. i guess [this](https://www.rdocumentation.org/packages/sp/versions/1.2-3/topics/spsample) answers my question

**Comment by joelgombin** [comment]
Or [this](https://rdrr.io/cran/sf/man/st_sample.html) to work directly with sf objects. 
Closing since this is not a concaveman-related issue.
