### ISSUE TITLE
issue with sf version?

### ISSUE THREAD

**Issue by jbeck11** [joelgombin/concaveman#5]
Greetings,

Is there perhaps a concaveman compatibility issue with sf version 0.6-1?  concaveman() currently doesn't return a SpatialpolygonDataframe, rather a SpatialMultiPointsDataFrame.  I'm running R 3.4.3 on RStudio 1.1.383, and sf version 0.6-1.  A colleague suggested this might be the case- happy to provide more details/code.

James

**Comment by joelgombin** [comment]
it works here: 

```r
library(concaveman)
library(sf)
data(points)
concaveman(points[points$k %in% 1,])
# Simple feature collection with 1 feature and 0 fields
# geometry type:  POLYGON
# dimension:      XY
# bbox:           xmin: -122.0844 ymin: 37.3802 xmax: -122.0785 ymax: 37.3873
# epsg (SRID):    4326
# proj4string:    +proj=longlat +datum=WGS84 +no_defs
```

Does it work with the latest `sf` version? Otherwise, could you provide a reproducible example?

**Comment by joelgombin** [comment]
Can I close this issue?
