### ISSUE TITLE
upcoming sf breaks concaveman checks

### ISSUE THREAD

**Issue by edzer** [joelgombin/concaveman#6]
With:
```r
> ### Name: concaveman
> ### Title: concaveman: A very fast 2D concave hull algorithm.
> ### Aliases: concaveman concaveman-package concaveman concave .... [TRUNCATED] 

> polygons <- concaveman(points)

> plot(points)

> plot(polygons, add = TRUE)
Error in if (cl %in% c("integer", "numeric")) stripchart(x1, ...) else plot(x1,  : 
  the condition has length > 1
> traceback()
6: plot.data.frame(polygons, add = TRUE)
5: plot(polygons, add = TRUE) at concaveman-Ex.R#37
4: eval(ei, envir)
3: eval(ei, envir)
2: withVisible(eval(ei, envir))
1: source("rdepends_concaveman.Rcheck/concaveman-Ex.R", , T)
```
If I later on do something with `points`, things run fine. Maybe load `sf` before running the example? Let me know if you need help.

**Comment by joelgombin** [comment]
Thanks @edzer and sorry for answering such a long time after you opened the issue!
With which version of `sf` did you try this?
If I try on my side (with sf 0.7-2, 
```r 
plot(polygons, add = TRUE)
```
throws a warning, not an error. Also, no polygon is drawn. So I guess the issue might be with the `plot.sf ` method? If I only do

```r 
plot(polygons)
```
I get the same warning but the polygon is actually drawn. What do yout hink?

**Comment by edzer** [comment]
I think these errors can be triggers when you set environment variables `_R_CHECK_LENGTH_1_LOGIC2_=package:_R_CHECK_PACKAGE_NAME_,abort,verbose`, or e.g. try with winbuilder.

**Comment by joelgombin** [comment]
Actually there's something strange. If I don't load `sf`, the output of `concaveman` is of class `data.frame` (where I would expect `sf - data.frame`). If I load `sf` before running `concaveman`, the output is of class `sf`...

**Comment by joelgombin** [comment]
``` r
library(concaveman)

class(points)
#> [1] "sf"         "data.frame"
polygon <- concaveman(points)
class(polygon)
#> [1] "data.frame"

library(sf)
#> Linking to GEOS 3.6.2, GDAL 2.2.3, PROJ 4.9.3

polygon <- concaveman(points)
class(polygon)
#> [1] "sf"         "data.frame"
```

<sup>Created on 2019-01-10 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by edzer** [comment]
That is because the `summarise.sf` method is only picked up (i.e., used) when `sf` is loaded. Without, you'll go through `summarise.data.frame`, provided by `dplyr`, which won't create `sf` objects.

**Comment by joelgombin** [comment]
Right. But I can't force the call to summarise.sf, can I ?

**Comment by edzer** [comment]
Your package needs to import it (can't see it in the NAMESPACE).

**Comment by joelgombin** [comment]
OK. But I wanted to avoid importing `sf` if it is not needed, and my understanding was that for S3 methods I didn't need to. See what [Hadley says](http://r-pkgs.had.co.nz/namespace.html):

> S3 generics are just functions, so the same rules for functions apply. S3 methods always accompany the generic, so as long as you can access the generic (either implicitly or explicitly), the methods will also be available. In other words, you don’t need to do anything special for S3 methods. As long as you’ve imported the generic, all the methods will also be available.

Am I getting it wrong?

**Comment by joelgombin** [comment]
BTW I've made sf a strong dependency to avoid this issue.
