### ISSUE TITLE
Replace js with new C++ implementation

### ISSUE THREAD

**Issue by mpadge** [joelgombin/concaveman#9]
The `.js` bundle requires `V8`, which is a big turn off for many. There is now (since May 2019) a newer, better C++ implementation [here](https://github.com/sadaszewski/concaveman-cpp), which just requires wrapping a [single header file](https://github.com/sadaszewski/concaveman-cpp/blob/master/src/main/cpp/concaveman.h). That would make this package far more portable and lighter. Do you want to give that a go? I'd be happy to help if you want

**Comment by joelgombin** [comment]
thanks @mpadge, I wasn't aware of the C++ implemetation. Getting rid of the `V8` dependancy would certainly be a huge improvement, i'll definitely look into it. Thanks for offering your help, I'll let you know if I don't manage to do it on my own!

**Comment by mpadge** [comment]
I'm bundling it anyway, so will basically be prototyping it for you regardless. It's got a [small issue](https://github.com/sadaszewski/concaveman-cpp/issues/3) at present that I hope to resolve in a couple of days, and then it should all be good to go. I'll let you know ...

**Comment by mpadge** [comment]
Hiya Joel, so I bundled the C++ version, and everything functions smoothly ... *but* ... it seems that it doesn't quite work, as shown here:
![junk](https://user-images.githubusercontent.com/6697851/60881671-76706a80-a246-11e9-82ed-4ee975b47d19.png)

The `V8` version works as expected on those data. That's a real shame, because the C++ version seems to be at least 10 times faster. Maybe you should feel free to close this in the meantime, and I'll report back if and when a functioning solution has been found. Sorry about that.

**Comment by joelgombin** [comment]
No problem. Closing it for now, don't hesitate to reopen it when the C++ version is ready, I'd like to learn to wrap a C++ function in R.

**Comment by mpadge** [comment]
Okay, it's all good - the mistake was my bad. I've bundled it [here](https://github.com/mpadge/mapscanner). The [header file (concaveman.h)](https://github.com/mpadge/mapscanner/blob/master/src/concaveman.h) is hardly changed from the [original](https://github.com/sadaszewski/concaveman-cpp/blob/master/src/main/cpp/concaveman.h), and all that needs to be added is something like  [this `.cpp` wrapper](https://github.com/mpadge/mapscanner/blob/master/src/concaveman.cpp). I can easily do it as a PR if you like, or you can use those as templates and try yourself. Let me know :smile: 

I'll leave benchmark results up to you, but you'll be able to compare by cloning the [`mapscanner` repo](https://github.com/mpadge/mapscanner), then running something like this:
``` r
devtools::load_all (".", export_all = TRUE)
npts <- 1000
xy <- data.frame (x = rnorm (npts), y = rnorm (npts))
h <- chull (xy)
cc <- rcpp_concaveman (xy, chull (xy) - 1, 1.0, 10.0)
```

**Comment by mpadge** [comment]
@joelgombin Just to let you know I've done a `.js` vs `.cpp` benchmark [here](https://github.com/mpadge/concavetest), with pretty clear results as expected. `cpp` is many times faster. Any time you want help bundling, let me know.

**Comment by joelgombin** [comment]
@mpadge I'm very sorry, for some reason I totally did not see your 07/12 comment. 
I'd love a PR, that would both help me learn to include C++ code in a package, and save me time (a sparse resource these days!). Thanks a lot!

**Comment by mpadge** [comment]
Sure - likely not til next week, but it's all very straightforward, so it shall be done promptly.

**Comment by joelgombin** [comment]
no problem, great!

**Comment by joelgombin** [comment]
FYI I'm preparing to release a new version (nothing new of substance), are you still thinking of proposing a C++ implementation?

**Comment by joelgombin** [comment]
(although I guess I could do it myself using your code from the concavetest package, if it's easier for you).

**Comment by mpadge** [comment]
Great timing - you might have seen twitter discussions with @dcooley from last week about exactly this issue. I'll get onto it and PR asap.
